# --- NVIDIA STACK ---
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct


env = AQ_NO_ATOMIC,1
env = WLR_DRM_NO_ATOMIC,1
env = __GL_MaxFramesAllowed,1
env = AQ_FORCE_LINEAR_BLIT,0

# --- THE RENDER BLOCK ---
render {
    new_render_scheduling = false  # STAYS OFF: This is the purple-killer.
}

misc {
    # If this is on, it can sometimes make resizing feel "heavy"
    vfr = true 
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
}


# --- THE CURSOR ---
cursor {
    no_hardware_cursors = true
    min_refresh_rate = 200        # This is what makes it feel "Fast"
    no_break_fs_vrr = true
}
